### PR TITLE
/j1a : Initial support for ice40HX8K Breakout Board

### PR DESCRIPTION
**Pull request by RGD2**
make -C icestorm j1a8k.bin will now produce an image for the HX8K breakout board.

This has a lot more space for extra logic.

### CODE REVIEW

**Comment by RGD2** [comment]
Hmm.. there is a wierd issue with this...
`true leds` outputs like `$6f leds`, `true true leds drop` works, but `true false leds drop` looks like `$90 dup leds drop`, wheras either `false false leds drop` or `false leds` works... except if the leds were already on then `true false leds drop` outputs like `$90 dup leds drop`.

In general, it seems to get the right output, `dup leds drop` is needed, and I'm not sure why. 
I think this is also affecting the other ports too - at first I thought that I just had the pins assigned wrong, but `: run 0 begin 1+ dup leds again ; run` worked.

I think it has to be a timing issue, possibly from the clock running too fast for the design as routed on this chip... `true dup 2 io! drop : run 0 begin dup 1 io! invert again ; run` yields a 2.66 MHz square wave on all the output pins, so it's running exactly as fast as the iCEStick version.

Unfortunately the Lattice documentation for the SB_PLL40_CORE just says "It is strongly recommended that the configuration of the PLL primitives be accomplished
through the use of the PLL Configuration tool that is offered as part of the iCEcube2 software. "

@jamesbowman How did you pick the DIVx parameter settings?

**Comment by RGD2** [comment]
Answers to my own question are at:

https://github.com/cliffordwolf/yosys/issues/107
https://github.com/carlosgs/iceDAQ/blob/master/pll_example/pll_example.v

**Comment by jamesbowman** [comment]
And application note from Lattice: "iCE40 sysCLOCK PLL Design and Usage Guide"

http://www.latticesemi.com/view_document?document_id=47778

**Comment by RGD2** [comment]
Oh, but apparently a more accurate reference for the PLL is at http://www.latticesemi.com/~/media/LatticeSemi/Documents/TechnicalBriefs/SBTICETechnologyLibrary201504.pdf

**Pull request merged**
